### ISSUE TITLE
Get the file name to add to deploy from the release version in spec

### ISSUE THREAD

**Issue by brucellino** [onedata/nagios-plugins-onedata#8]
the travis file has a continuous deployment endpoint using [github releases](https://docs.travis-ci.com/user/deployment/releases/) : 

```
deploy:
  provider: releases
  api_key:
  file:
    - nagios-plugins-onedata-3.2.0-1.el6.noarch.rpm
  on:
    tags: true
```

We need the file uploaded with the correct name (ie, including the release that has been tagged being the same as the release in the spec)

If you want, I can work on this.
